export type ErrorCode =
    | 'SOURCE_INVALID_RESPONSE'
    | 'SOURCE_RATE_LIMITED'
    | 'SOURCE_UNAVAILABLE'
    | 'PERSISTENCE_DUPLICATE_KEY'
    | 'PERSISTENCE_UNAVAILABLE'
    | 'VALIDATION_FAILED'
    | 'UNKNOWN';


